# Generated by Django 4.1 on 2022-12-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_monthlysales_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysales',
            name='sale_id',
            field=models.DateField(db_column='sale_id', primary_key=True, serialize=False),
        ),
    ]
