# Generated by Django 4.1 on 2022-12-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_month_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month_sale',
            name='sale_id',
            field=models.CharField(db_column='sale_id', max_length=7, primary_key=True, serialize=False),
        ),
    ]
