# Generated by Django 4.1 on 2022-12-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_alter_month_sale_sale_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='month_sale',
            new_name='year_sale',
        ),
    ]
