# Generated by Django 4.1.4 on 2022-12-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_monthlysales_cancel_ticket_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysales',
            name='refund_ticket_amount',
            field=models.DecimalField(blank=True, db_column='refund_ticket_amount', decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='monthlysales',
            name='refund_ticket_qty',
            field=models.IntegerField(blank=True, db_column='refund_ticket_qty', null=True),
        ),
    ]
