# Generated by Django 4.1.4 on 2022-12-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_monthlysales_refund_ticket_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysales',
            name='user_qty',
            field=models.IntegerField(blank=True, db_column='user_qty', null=True),
        ),
    ]
