# Generated by Django 4.1.4 on 2022-12-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0011_monthlysales_user_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysales',
            name='cancel_ticket_amount',
            field=models.DecimalField(blank=True, db_column='cancel_ticket_amount', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='cancel_ticket_qty',
            field=models.IntegerField(blank=True, db_column='cancel_ticket_qty', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='daily_sale',
            field=models.DecimalField(blank=True, db_column='daily_sale', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='pending_ticket_amount',
            field=models.DecimalField(blank=True, db_column='pending_ticket_amount', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='pending_ticket_qty',
            field=models.IntegerField(blank=True, db_column='pending_ticket_qty', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='refund_ticket_amount',
            field=models.DecimalField(blank=True, db_column='refund_ticket_amount', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='refund_ticket_qty',
            field=models.IntegerField(blank=True, db_column='refund_ticket_qty', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='total_ticket_qty',
            field=models.IntegerField(blank=True, db_column='total_ticket_qty', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='used_ticket_amount',
            field=models.DecimalField(blank=True, db_column='used_ticket_amount', decimal_places=2, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='used_ticket_qty',
            field=models.IntegerField(blank=True, db_column='used_ticket_qty', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='monthlysales',
            name='user_qty',
            field=models.IntegerField(blank=True, db_column='user_qty', default=0, null=True),
        ),
    ]
