# Generated by Django 4.1 on 2022-10-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdestinations',
            name='picture_url',
            field=models.URLField(db_column='picture_url', null=True),
        ),
    ]
