# Generated by Django 4.1 on 2022-10-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_postdestinations_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdestinations',
            name='picture',
            field=models.ImageField(db_column='picture', null=True, upload_to=''),
        ),
    ]
