# Generated by Django 4.1 on 2022-10-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_postdestinations_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdestinations',
            name='picture',
            field=models.ImageField(blank=True, db_column='picture', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postdestinations',
            name='picture_url',
            field=models.URLField(blank=True, db_column='picture_url', null=True),
        ),
    ]
