# Generated by Django 4.1 on 2022-10-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_busdetails_route_date_alter_routes_bus_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='agreement',
            field=models.BooleanField(db_column='agreement', default=None),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.BooleanField(db_column='gender', default=None),
            preserve_default=False,
        ),
    ]
