# Generated by Django 4.1 on 2022-10-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_passenger_agreement_passenger_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.BooleanField(choices=[('1', 'Male'), ('2', 'Female')], db_column='gender'),
        ),
    ]
