# Generated by Django 4.1 on 2022-10-23 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_passenger_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busseat',
            name='no_of_seat',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='gender',
        ),
    ]
