# Generated by Django 4.1 on 2022-10-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_passenger_select_bus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusSeatDetails',
            fields=[
                ('seat_details_id', models.AutoField(db_column='seat_detail_id', primary_key=True, serialize=False)),
                ('seat_number', models.CharField(db_column='seat_number', max_length=2)),
            ],
            options={
                'db_table': 'bus_seat_detail',
            },
        ),
        migrations.RemoveField(
            model_name='busseat',
            name='seat_no',
        ),
        migrations.AddField(
            model_name='busdetails',
            name='no_of_seat',
            field=models.IntegerField(blank=True, db_column='no_of_seat', null=True),
        ),
        migrations.AddField(
            model_name='busseat',
            name='bus_seat_data',
            field=models.ForeignKey(db_column='seat_detail_id', default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='main.busseatdetails'),
            preserve_default=False,
        ),
    ]
