# Generated by Django 4.1 on 2022-10-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_busseatdetails_remove_busseat_seat_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='bus_seat_data',
            field=models.ForeignKey(db_column='bus_seat_data', on_delete=django.db.models.deletion.DO_NOTHING, to='main.busseatdetails'),
        ),
    ]
