# Generated by Django 4.1 on 2022-10-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_busseat_bus_seat_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='bus_seat_data',
            field=models.ForeignKey(db_column='seat_detail_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.busseatdetails'),
        ),
    ]
