# Generated by Django 4.1 on 2022-10-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_busseat_bus_seat_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busseat',
            name='booking_status',
        ),
        migrations.RemoveField(
            model_name='busseat',
            name='bus_plate_no',
        ),
        migrations.RemoveField(
            model_name='busseat',
            name='bus_seat_data',
        ),
        migrations.RemoveField(
            model_name='busseat',
            name='passengerID',
        ),
        migrations.AddField(
            model_name='busbookingdetails',
            name='booking_status',
            field=models.BooleanField(blank=True, db_column='booking_status', null=True),
        ),
        migrations.AddField(
            model_name='busseat',
            name='seat_no',
            field=models.IntegerField(db_column='seat_no', default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busseat',
            name='seat_id',
            field=models.CharField(db_column='seat_id', max_length=3, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BusSeatDetails',
        ),
    ]
