# Generated by Django 4.1 on 2022-10-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_busseat_booking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='seat_no',
            field=models.IntegerField(db_column='seat_no'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='otherDetails',
            field=models.CharField(blank=True, db_column='otherDetails', max_length=200, null=True),
        ),
    ]
