# Generated by Django 4.1 on 2022-10-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_busseat_seat_no_alter_owner_otherdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbookingdetails',
            name='booking_status',
            field=models.BooleanField(blank=True, db_column='booking_status', default=0, null=True),
        ),
    ]
