# Generated by Django 4.1 on 2022-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_busbookingdetails_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='agreement',
            field=models.BooleanField(db_column='agreement', default=0),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passengerID',
            field=models.AutoField(db_column='PassengerDetailId', primary_key=True, serialize=False),
        ),
    ]
