# Generated by Django 4.1 on 2022-10-24 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_passenger_agreement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbookingdetails',
            name='passengerID',
            field=models.ForeignKey(db_column='PassengerDetailId', on_delete=django.db.models.deletion.DO_NOTHING, to='main.passenger'),
        ),
    ]
