# Generated by Django 4.1 on 2022-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_busbookingdetails_passengerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busseat',
            name='seat_id',
            field=models.IntegerField(db_column='seat_id', max_length=2, primary_key=True, serialize=False),
        ),
    ]
