# Generated by Django 4.1 on 2022-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_busseat_seat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbookingdetails',
            name='c_time',
            field=models.DateTimeField(blank=True, db_column='c_time'),
        ),
    ]
