# Generated by Django 4.1 on 2022-10-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_busbookingdetails_c_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbookingdetails',
            name='c_time',
            field=models.DateTimeField(auto_now_add=True, db_column='c_time'),
        ),
    ]
