# Generated by Django 4.1 on 2022-10-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_busbookingdetails_c_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxi',
            name='username',
        ),
        migrations.RemoveField(
            model_name='taxibookingdetails',
            name='passengerID',
        ),
        migrations.RemoveField(
            model_name='taxibookingdetails',
            name='taxi_detail',
        ),
        migrations.RemoveField(
            model_name='taxibookingdetails',
            name='taxi_plate_no',
        ),
        migrations.RemoveField(
            model_name='taxidetails',
            name='taxi_plate_no',
        ),
        migrations.RemoveField(
            model_name='taxireceipt',
            name='passengerID',
        ),
        migrations.RemoveField(
            model_name='taxireceipt',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='taxireceipt',
            name='taxi_detail_id',
        ),
        migrations.RemoveField(
            model_name='taxireceipt',
            name='taxi_plate_no',
        ),
        migrations.RemoveField(
            model_name='busbookingdetails',
            name='seat_id',
        ),
        migrations.RemoveField(
            model_name='busticket',
            name='seat_id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='userSearch_taxi',
        ),
        migrations.RemoveField(
            model_name='passengerpayment',
            name='taxi_book_id',
        ),
        migrations.AddField(
            model_name='busbookingdetails',
            name='seat_no',
            field=models.IntegerField(db_column='seat_no', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passenger',
            name='select_bus',
            field=models.ManyToManyField(to='main.bus'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='userSelectRoutes',
            field=models.ManyToManyField(to='main.routes'),
        ),
        migrations.DeleteModel(
            name='BusSeat',
        ),
        migrations.DeleteModel(
            name='Taxi',
        ),
        migrations.DeleteModel(
            name='TaxiBookingDetails',
        ),
        migrations.DeleteModel(
            name='TaxiDetails',
        ),
        migrations.DeleteModel(
            name='TaxiReceipt',
        ),
    ]
