# Generated by Django 4.1 on 2022-11-05 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_taxi_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='lastname',
        ),
    ]
