# Generated by Django 4.1 on 2022-11-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_passenger_firstname_remove_passenger_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengerpayment',
            name='card_type',
        ),
    ]
