# Generated by Django 4.1 on 2022-11-24 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_passengerpayment_card_type'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postdestinations',
            table='post',
        ),
        migrations.CreateModel(
            name='GiveFeedBack',
            fields=[
                ('feed_back_id', models.AutoField(db_column='feed_back_id', primary_key=True, serialize=False)),
                ('f_name', models.CharField(db_column='first_name', max_length=25)),
                ('l_name', models.CharField(db_column='last_name', max_length=25)),
                ('message', models.CharField(db_column='message', max_length=500)),
                ('message_status', models.BooleanField(default=0, verbose_name='status')),
                ('owner_name', models.ForeignKey(db_column='userName', on_delete=django.db.models.deletion.DO_NOTHING, to='main.owner')),
            ],
            options={
                'db_table': 'feed_back',
            },
        ),
    ]
