# Generated by Django 4.1 on 2022-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_subemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subemail',
            name='sub_id',
        ),
        migrations.AlterField(
            model_name='subemail',
            name='email_name',
            field=models.EmailField(db_column='email_address', max_length=254, primary_key=True, serialize=False),
        ),
    ]
