# Generated by Django 4.1 on 2022-11-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_alter_busdetails_total_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busdetails',
            name='total_distance',
            field=models.DecimalField(blank=True, db_column='totalDistance', decimal_places=2, max_digits=4, null=True),
        ),
    ]
