# Generated by Django 4.1 on 2022-11-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_busdetails_total_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='telePhoneNo',
        ),
        migrations.AddField(
            model_name='passenger',
            name='emailaddr',
            field=models.CharField(blank=True, db_column='emailaddr', max_length=50, null=True),
        ),
    ]
