# Generated by Django 4.1 on 2022-11-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_remove_passenger_telephoneno_passenger_emailaddr'),
    ]

    operations = [
        migrations.AddField(
            model_name='busticket',
            name='invoiceno',
            field=models.CharField(blank=True, db_column='invoice', max_length=15, null=True),
        ),
    ]
