# Generated by Django 4.1 on 2022-11-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_busticket_invoiceno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busbookingdetails',
            name='bus_data',
        ),
        migrations.RemoveField(
            model_name='busticket',
            name='bus_data_id',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='bus_data_id',
        ),
        migrations.AddField(
            model_name='bus',
            name='avg_run_time',
            field=models.DecimalField(blank=True, db_column='avgRunTime', decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='contact_no',
            field=models.CharField(blank=True, db_column='contactNo', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='no_of_seat',
            field=models.IntegerField(blank=True, db_column='no_of_seat', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='other_details',
            field=models.TextField(blank=True, db_column='otherDetails', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='vehicle_status',
            field=models.BooleanField(blank=True, db_column='vehicleStatus', null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='end_location',
            field=models.CharField(blank=True, db_column='endLocation', default='None', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='route_date',
            field=models.DateField(blank=True, db_column='routeDate', null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='route_no',
            field=models.CharField(blank=True, db_column='routeNo', default='None', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='route_time',
            field=models.TimeField(blank=True, db_column='routeTime', null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='start_location',
            field=models.CharField(blank=True, db_column='startLocation', default='None', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='routes',
            name='total_distance',
            field=models.DecimalField(blank=True, db_column='totalDistance', decimal_places=2, max_digits=4, null=True),
        ),
        migrations.DeleteModel(
            name='busDetails',
        ),
    ]
