# Generated by Django 4.1 on 2022-11-30 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_remove_busbookingdetails_bus_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='avg_run_time',
        ),
        migrations.AddField(
            model_name='routes',
            name='avg_run_time',
            field=models.DecimalField(blank=True, db_column='avgRunTime', decimal_places=2, max_digits=4, null=True),
        ),
    ]
