# Generated by Django 4.1 on 2022-11-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_bus_avg_run_time_routes_avg_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='routes',
            name='vehicle_status',
            field=models.BooleanField(blank=True, db_column='vehicleStatus', null=True),
        ),
    ]
