# Generated by Django 4.1 on 2022-12-02 23:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_rename_vehicle_status_routes_route_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='newsAndUpdate',
            fields=[
                ('newsandupdate_id', models.AutoField(db_column='newsandupdate_id', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_column='subject', max_length=200)),
                ('email', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
