# Generated by Django 4.1 on 2022-12-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_newsandupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='givefeedback',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True, db_column='date', default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='givefeedback',
            name='message_status',
            field=models.IntegerField(db_column='status', default=0),
        ),
    ]
