# Generated by Django 4.1 on 2022-12-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_busticket_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='busticket',
            name='ticket_expire_date',
            field=models.DateTimeField(blank=True, db_column='expire_date', null=True),
        ),
    ]
