# Generated by Django 4.1 on 2022-12-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_busticket_c_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='busticket',
            name='ticket_counted',
            field=models.BooleanField(blank=True, db_column='ticket_count', null=True),
        ),
    ]
