# Generated by Django 4.1 on 2022-12-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_busticket_ticket_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busticket',
            name='ticket_qr_code',
            field=models.ImageField(blank=True, db_column='qr_code', null=True, upload_to='upload/'),
        ),
    ]
