# Generated by Django 4.1 on 2022-12-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_busticket_ticket_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busticket',
            name='ticket_qr_code',
            field=models.ImageField(blank=True, db_column='qr_code', null=True, upload_to='media/'),
        ),
    ]
