# Generated by Django 4.1 on 2022-12-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_alter_busticket_ticket_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticketRefund',
            fields=[
                ('ticket_id', models.AutoField(db_column='ticket_id', primary_key=True, serialize=False)),
                ('total_amount', models.IntegerField(blank=True, db_column='total_amount', null=True)),
                ('company_name', models.CharField(blank=True, db_column='company_name', max_length=30, null=True)),
                ('ticket_status', models.IntegerField(db_column='ticket_status', default=1)),
                ('c_time', models.DateTimeField(blank=True, db_column='c_time')),
                ('ticket_expire_date', models.DateTimeField(blank=True, db_column='expire_date', null=True)),
                ('invoiceno', models.CharField(blank=True, db_column='invoice', max_length=15, null=True)),
                ('ticket_counted', models.BooleanField(blank=True, db_column='ticket_count', default=0, null=True)),
                ('ticket_qr_code', models.ImageField(blank=True, db_column='qr_code', null=True, upload_to='media/')),
                ('bus_plate_no', models.ForeignKey(db_column='bus_plate_no', on_delete=django.db.models.deletion.DO_NOTHING, to='main.bus')),
                ('passengerID', models.ForeignKey(db_column='passengerID', on_delete=django.db.models.deletion.DO_NOTHING, to='main.passenger')),
                ('payment_id', models.ForeignKey(db_column='payment_id', on_delete=django.db.models.deletion.DO_NOTHING, to='main.passengerpayment')),
            ],
            options={
                'db_table': 'refund_ticket',
            },
        ),
    ]
