# Generated by Django 4.1.4 on 2022-12-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_ticketrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='busticket',
            name='ticket_cancel_counted',
            field=models.BooleanField(blank=True, db_column='ticket_cancel_counted', default=0, null=True),
        ),
        migrations.AddField(
            model_name='busticket',
            name='ticket_refund_counted',
            field=models.BooleanField(blank=True, db_column='ticket_refund_counted', default=0, null=True),
        ),
        migrations.AddField(
            model_name='busticket',
            name='ticket_used_counted',
            field=models.BooleanField(blank=True, db_column='ticket_used_counted', default=0, null=True),
        ),
    ]
