# Generated by Django 4.1.4 on 2022-12-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_busticket_ticket_cancel_counted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passenger_count',
            field=models.BooleanField(blank=True, db_column='passenger_qty', default=0, null=True),
        ),
    ]
