# Generated by Django 4.1.4 on 2022-12-24 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0050_passenger_passenger_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='postdestinations',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='bus',
            name='user',
            field=models.OneToOneField(db_column='userName', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postdestinations',
            name='user',
            field=models.OneToOneField(db_column='userName', default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routes',
            name='avg_run_time',
            field=models.DecimalField(blank=True, db_column='avgRunTime', decimal_places=2, max_digits=4, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='routes',
            name='total_distance',
            field=models.DecimalField(blank=True, db_column='totalDistance', decimal_places=2, max_digits=4, max_length=5, null=True),
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
