# Generated by Django 4.1.4 on 2022-12-24 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0053_rename_user_bus_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='userName',
            field=models.OneToOneField(blank=True, db_column='userName', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postdestinations',
            name='userName',
            field=models.OneToOneField(blank=True, db_column='userName', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
