# Generated by Django 4.1.4 on 2022-12-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_alter_bus_username_alter_postdestinations_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='total_distance',
            field=models.DecimalField(blank=True, db_column='totalDistance', decimal_places=2, max_digits=8, max_length=10, null=True),
        ),
    ]
