# Generated by Django 4.1.4 on 2022-12-26 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_alter_routes_total_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbookingdetails',
            name='route_time_actual',
            field=models.ForeignKey(blank=True, db_column='routeTime', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.routes'),
        ),
    ]
