# Generated by Django 4.1.4 on 2022-12-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_busbookingdetails_route_time_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busbookingdetails',
            name='route_time_actual',
            field=models.TimeField(blank=True, db_column='routeTime', null=True),
        ),
    ]
