# Generated by Django 4.1.4 on 2022-12-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_alter_busbookingdetails_route_time_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, db_column='registerdate', default=None),
            preserve_default=False,
        ),
    ]
