# Generated by Django 4.1.4 on 2023-01-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_alter_bus_register_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subemail',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True, db_column='date', default=None),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='newsandupdate',
            table='newsandupdate',
        ),
    ]
