# Generated by Django 4.1.4 on 2023-01-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_subemail_reg_date_alter_newsandupdate_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbookingdetails',
            name='booked_date',
            field=models.DateField(blank=True, db_column='booked_date', null=True),
        ),
    ]
