# Generated by Django 4.1.4 on 2023-01-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_alter_routes_route_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subemail',
            name='reg_date',
        ),
    ]
