# Generated by Django 4.1.4 on 2023-01-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_remove_subemail_reg_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='vehicle_status',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='avg_run_time',
        ),
    ]
