# Generated by Django 4.1.4 on 2023-01-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_remove_bus_vehicle_status_remove_routes_avg_run_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='vehicle_status',
            field=models.BooleanField(blank=True, db_column='vehicleStatus', null=True),
        ),
    ]
